from .azure import AzureWorker
from .baichuan import BaiChuanWorker
from .base import *
from .fangzhou import FangZhouWorker
from .minimax import MiniMaxWorker
from .qianfan import QianFanWorker
from .qwen import QwenWorker
from .xinghuo import XingHuoWorker
from .zhipu import ChatGLMWorker
